{"Proper way to declare custom exceptions in modern Python?": 6}