{"Catch a thread&#39;s exception in the caller thread in Python": 12}